name: come_along_with_me
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  image_picker: ^1.0.0
  intl: ^0.18.1
  lottie: ^2.4.0
  percent_indicator: ^4.2.3
  google_sign_in: ^6.1.4
  firebase_core: ^2.14.0
  mailer: ^6.0.1
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  permission_handler: ^10.4.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  shared_preferences: ^2.2.1
  flutter_cache_manager: ^3.3.1
  flutter_sound: ^9.2.13
  audioplayers: ^5.1.0
  assets_audio_player: ^3.1.1
  android_media: ^0.0.1
  url_launcher: ^6.1.14 
flutter_launcher_icons: 
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/icon/launcher_logo.png'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/.
    - assets/onlymp3.to - Danger Alarm Sound Effect-rUkzZTGE6jI-192k-1695664567.mp3

